# Generated by Django 6.0.4 on 2026-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='kyc_documents/'),
        ),
    ]
